using System.Linq;
using System.Collections.Generic;
using Bws.Bible.Core.Extensions;

namespace Bws.Bible.Api.Routing
{
    /// <summary>
    /// Résolveur d'acronymes et de noms des livres de la Bible
    /// </summary>
    public static class BookResolver
    {
        /// <summary>
        /// Obtenir l'identifiant d'un livre de la Bible à partir de la chaine de caractère entrante.
        /// </summary>
        /// <param name="book">Acronyme, numéro, ou titre du livre</param>
        /// <returns>Identifiant du livre</returns>
        public static byte GetBookNumber(string book)
        {
            if (byte.TryParse(book, out byte bookNumber))
            {
                return bookNumber;
            }

            string refToFind = book.ToLowerInvariant().RemoveDiacritics();
            BookRef bookRef = booksRefByName.Where(b => b.Ref.Equals(refToFind)).FirstOrDefault();
            if (bookRef.Id > 0)
            {
                return bookRef.Id;
            }
            bookRef = booksRefByAbv.Where(b => b.Ref.Equals(refToFind)).FirstOrDefault();
            if (bookRef.Id > 0)
            {
                return bookRef.Id;
            }

            return 0;
        }

        private struct BookRef
        {
            public byte Id { get; set; }
            public string Ref { get; set; }
        }

        private static readonly List<BookRef> booksRefByName = new List<BookRef>()
        {
            new BookRef(){ Id = 1, Ref = "genese" },
            new BookRef(){ Id = 2, Ref = "exode" },
            new BookRef(){ Id = 3, Ref = "levitique" },
            new BookRef(){ Id = 4, Ref = "nombres" },
            new BookRef(){ Id = 5, Ref = "deuteronome" },
            new BookRef(){ Id = 6, Ref = "josue" },
            new BookRef(){ Id = 7, Ref = "juges" },
            new BookRef(){ Id = 8, Ref = "ruth" },
            new BookRef(){ Id = 9, Ref = "1samuel" },
            new BookRef(){ Id = 9, Ref = "samuel1" },
            new BookRef(){ Id = 10, Ref = "2samuel" },
            new BookRef(){ Id = 10, Ref = "samuel2" },
            new BookRef(){ Id = 11, Ref = "1rois" },
            new BookRef(){ Id = 11, Ref = "rois1" },
            new BookRef(){ Id = 12, Ref = "2rois" },
            new BookRef(){ Id = 12, Ref = "rois2" },
            new BookRef(){ Id = 13, Ref = "1chroniques" },
            new BookRef(){ Id = 13, Ref = "chroniques1" },
            new BookRef(){ Id = 14, Ref = "2chroniques" },
            new BookRef(){ Id = 14, Ref = "chroniques2" },
            new BookRef(){ Id = 15, Ref = "esdras" },
            new BookRef(){ Id = 16, Ref = "nehemie" },
            new BookRef(){ Id = 17, Ref = "esther" },
            new BookRef(){ Id = 18, Ref = "job" },
            new BookRef(){ Id = 19, Ref = "psaumes" },
            new BookRef(){ Id = 20, Ref = "proverbes" },
            new BookRef(){ Id = 21, Ref = "ecclesiaste" },
            new BookRef(){ Id = 22, Ref = "cantique" },
            new BookRef(){ Id = 23, Ref = "esaie" },
            new BookRef(){ Id = 24, Ref = "jeremie" },
            new BookRef(){ Id = 25, Ref = "lamentations" },
            new BookRef(){ Id = 26, Ref = "ezechiel" },
            new BookRef(){ Id = 27, Ref = "daniel" },
            new BookRef(){ Id = 28, Ref = "osee" },
            new BookRef(){ Id = 29, Ref = "joel" },
            new BookRef(){ Id = 30, Ref = "amos" },
            new BookRef(){ Id = 31, Ref = "abdias" },
            new BookRef(){ Id = 32, Ref = "jonas" },
            new BookRef(){ Id = 33, Ref = "michee" },
            new BookRef(){ Id = 34, Ref = "nahum" },
            new BookRef(){ Id = 35, Ref = "habacuc" },
            new BookRef(){ Id = 36, Ref = "sophonie" },
            new BookRef(){ Id = 37, Ref = "aggee" },
            new BookRef(){ Id = 38, Ref = "zacharie" },
            new BookRef(){ Id = 39, Ref = "malachie" },
            new BookRef(){ Id = 40, Ref = "matthieu" },
            new BookRef(){ Id = 41, Ref = "marc" },
            new BookRef(){ Id = 42, Ref = "luc" },
            new BookRef(){ Id = 43, Ref = "jean" },
            new BookRef(){ Id = 44, Ref = "actes" },
            new BookRef(){ Id = 45, Ref = "romains" },
            new BookRef(){ Id = 46, Ref = "1corinthiens" },
            new BookRef(){ Id = 46, Ref = "corinthiens1" },
            new BookRef(){ Id = 47, Ref = "2corinthiens" },
            new BookRef(){ Id = 47, Ref = "corinthiens2" },
            new BookRef(){ Id = 48, Ref = "galates" },
            new BookRef(){ Id = 49, Ref = "ephesiens" },
            new BookRef(){ Id = 50, Ref = "philippiens" },
            new BookRef(){ Id = 51, Ref = "colossiens" },
            new BookRef(){ Id = 52, Ref = "1thessaloniciens" },
            new BookRef(){ Id = 52, Ref = "thessaloniciens1" },
            new BookRef(){ Id = 53, Ref = "2thessaloniciens" },
            new BookRef(){ Id = 53, Ref = "thessaloniciens2" },
            new BookRef(){ Id = 54, Ref = "1timothee" },
            new BookRef(){ Id = 54, Ref = "timothee1" },
            new BookRef(){ Id = 55, Ref = "2timothee" },
            new BookRef(){ Id = 55, Ref = "timothee2" },
            new BookRef(){ Id = 56, Ref = "tite" },
            new BookRef(){ Id = 57, Ref = "philemon" },
            new BookRef(){ Id = 58, Ref = "hebreux" },
            new BookRef(){ Id = 59, Ref = "jacques" },
            new BookRef(){ Id = 60, Ref = "1pierre" },
            new BookRef(){ Id = 60, Ref = "pierre1" },
            new BookRef(){ Id = 61, Ref = "2pierre" },
            new BookRef(){ Id = 61, Ref = "pierre2" },
            new BookRef(){ Id = 62, Ref = "1jean" },
            new BookRef(){ Id = 62, Ref = "jean1" },
            new BookRef(){ Id = 63, Ref = "2jean" },
            new BookRef(){ Id = 63, Ref = "jean2" },
            new BookRef(){ Id = 64, Ref = "3jean" },
            new BookRef(){ Id = 64, Ref = "jean3" },
            new BookRef(){ Id = 65, Ref = "jude" },
            new BookRef(){ Id = 66, Ref = "apocalypse" },
        };

        private static readonly List<BookRef> booksRefByAbv = new List<BookRef>()
        {
            new BookRef(){ Id = 1, Ref = "gn" },
            new BookRef(){ Id = 1, Ref = "ge" },
            new BookRef(){ Id = 1, Ref = "gen" },
            new BookRef(){ Id = 2, Ref = "ex" },
            new BookRef(){ Id = 3, Ref = "lv" },
            new BookRef(){ Id = 3, Ref = "lev" },
            new BookRef(){ Id = 4, Ref = "nb" },
            new BookRef(){ Id = 4, Ref = "nom" },
            new BookRef(){ Id = 5, Ref = "dt" },
            new BookRef(){ Id = 5, Ref = "deut" },
            new BookRef(){ Id = 6, Ref = "js" },
            new BookRef(){ Id = 6, Ref = "jos" },
            new BookRef(){ Id = 7, Ref = "jg" },
            new BookRef(){ Id = 7, Ref = "jug" },
            new BookRef(){ Id = 8, Ref = "rt" },
            new BookRef(){ Id = 8, Ref = "ru" },
            new BookRef(){ Id = 9, Ref = "1s" },
            new BookRef(){ Id = 9, Ref = "s1" },
            new BookRef(){ Id = 10, Ref = "2s" },
            new BookRef(){ Id = 10, Ref = "s2" },
            new BookRef(){ Id = 11, Ref = "1r" },
            new BookRef(){ Id = 11, Ref = "r1" },
            new BookRef(){ Id = 12, Ref = "2r" },
            new BookRef(){ Id = 12, Ref = "r2" },
            new BookRef(){ Id = 13, Ref = "1ch" },
            new BookRef(){ Id = 13, Ref = "ch1" },
            new BookRef(){ Id = 14, Ref = "2ch" },
            new BookRef(){ Id = 14, Ref = "ch2" },
            new BookRef(){ Id = 15, Ref = "ed" },
            new BookRef(){ Id = 15, Ref = "esd" },
            new BookRef(){ Id = 16, Ref = "nh" },
            new BookRef(){ Id = 16, Ref = "ne" },
            new BookRef(){ Id = 17, Ref = "et" },
            new BookRef(){ Id = 17, Ref = "est" },
            new BookRef(){ Id = 18, Ref = "jb" },
            new BookRef(){ Id = 18, Ref = "job" },
            new BookRef(){ Id = 19, Ref = "ps" },
            new BookRef(){ Id = 20, Ref = "pv" },
            new BookRef(){ Id = 21, Ref = "ec" },
            new BookRef(){ Id = 21, Ref = "ecc" },
            new BookRef(){ Id = 22, Ref = "ct" },
            new BookRef(){ Id = 22, Ref = "cant" },
            new BookRef(){ Id = 23, Ref = "es" },
            new BookRef(){ Id = 23, Ref = "is" },
            new BookRef(){ Id = 24, Ref = "jr" },
            new BookRef(){ Id = 24, Ref = "je" },
            new BookRef(){ Id = 25, Ref = "la" },
            new BookRef(){ Id = 25, Ref = "lm" },
            new BookRef(){ Id = 25, Ref = "lam" },
            new BookRef(){ Id = 26, Ref = "ez" },
            new BookRef(){ Id = 27, Ref = "da" },
            new BookRef(){ Id = 27, Ref = "dn" },
            new BookRef(){ Id = 28, Ref = "os" },
            new BookRef(){ Id = 29, Ref = "jl" },
            new BookRef(){ Id = 29, Ref = "joe" },
            new BookRef(){ Id = 30, Ref = "am" },
            new BookRef(){ Id = 31, Ref = "ab" },
            new BookRef(){ Id = 31, Ref = "abd" },
            new BookRef(){ Id = 32, Ref = "jon" },
            new BookRef(){ Id = 33, Ref = "mi" },
            new BookRef(){ Id = 34, Ref = "na" },
            new BookRef(){ Id = 34, Ref = "nah" },
            new BookRef(){ Id = 35, Ref = "ha" },
            new BookRef(){ Id = 35, Ref = "hab" },
            new BookRef(){ Id = 36, Ref = "so" },
            new BookRef(){ Id = 37, Ref = "ag" },
            new BookRef(){ Id = 37, Ref = "agg" },
            new BookRef(){ Id = 38, Ref = "za" },
            new BookRef(){ Id = 39, Ref = "ml" },
            new BookRef(){ Id = 39, Ref = "ma" },
            new BookRef(){ Id = 40, Ref = "mt" },
            new BookRef(){ Id = 40, Ref = "mat" },
            new BookRef(){ Id = 40, Ref = "matt" },
            new BookRef(){ Id = 41, Ref = "mc" },
            new BookRef(){ Id = 41, Ref = "mar" },
            new BookRef(){ Id = 42, Ref = "lc" },
            new BookRef(){ Id = 43, Ref = "j" },
            new BookRef(){ Id = 43, Ref = "jn" },
            new BookRef(){ Id = 44, Ref = "ac" },
            new BookRef(){ Id = 44, Ref = "act" },
            new BookRef(){ Id = 45, Ref = "rm" },
            new BookRef(){ Id = 45, Ref = "ro" },
            new BookRef(){ Id = 45, Ref = "rom" },
            new BookRef(){ Id = 46, Ref = "1cr" },
            new BookRef(){ Id = 46, Ref = "1co" },
            new BookRef(){ Id = 46, Ref = "1cor" },
            new BookRef(){ Id = 46, Ref = "cr1" },
            new BookRef(){ Id = 46, Ref = "co1" },
            new BookRef(){ Id = 46, Ref = "cor1" },
            new BookRef(){ Id = 47, Ref = "2cr" },
            new BookRef(){ Id = 47, Ref = "2co" },
            new BookRef(){ Id = 47, Ref = "2cor" },
            new BookRef(){ Id = 47, Ref = "cr2" },
            new BookRef(){ Id = 47, Ref = "co2" },
            new BookRef(){ Id = 47, Ref = "cor2" },
            new BookRef(){ Id = 48, Ref = "ga" },
            new BookRef(){ Id = 48, Ref = "gl" },
            new BookRef(){ Id = 48, Ref = "gal" },
            new BookRef(){ Id = 49, Ref = "ep" },
            new BookRef(){ Id = 49, Ref = "eph" },
            new BookRef(){ Id = 50, Ref = "ph" },
            new BookRef(){ Id = 50, Ref = "phil" },
            new BookRef(){ Id = 51, Ref = "cl" },
            new BookRef(){ Id = 51, Ref = "co" },
            new BookRef(){ Id = 51, Ref = "col" },
            new BookRef(){ Id = 52, Ref = "1th" },
            new BookRef(){ Id = 52, Ref = "1thes" },
            new BookRef(){ Id = 52, Ref = "1thess" },
            new BookRef(){ Id = 52, Ref = "th1" },
            new BookRef(){ Id = 52, Ref = "thes1" },
            new BookRef(){ Id = 52, Ref = "thess1" },
            new BookRef(){ Id = 53, Ref = "2th" },
            new BookRef(){ Id = 53, Ref = "2thes" },
            new BookRef(){ Id = 53, Ref = "2thess" },
            new BookRef(){ Id = 53, Ref = "th2" },
            new BookRef(){ Id = 53, Ref = "thes2" },
            new BookRef(){ Id = 53, Ref = "thess2" },
            new BookRef(){ Id = 54, Ref = "1tm" },
            new BookRef(){ Id = 54, Ref = "1ti" },
            new BookRef(){ Id = 54, Ref = "tm1" },
            new BookRef(){ Id = 54, Ref = "ti1" },
            new BookRef(){ Id = 55, Ref = "2tm" },
            new BookRef(){ Id = 55, Ref = "2ti" },
            new BookRef(){ Id = 55, Ref = "tm2" },
            new BookRef(){ Id = 55, Ref = "ti2" },
            new BookRef(){ Id = 56, Ref = "tt" },
            new BookRef(){ Id = 56, Ref = "tit" },
            new BookRef(){ Id = 57, Ref = "pm" },
            new BookRef(){ Id = 57, Ref = "phm" },
            new BookRef(){ Id = 58, Ref = "hb" },
            new BookRef(){ Id = 58, Ref = "he" },
            new BookRef(){ Id = 59, Ref = "jc" },
            new BookRef(){ Id = 59, Ref = "jac" },
            new BookRef(){ Id = 59, Ref = "jq" },
            new BookRef(){ Id = 60, Ref = "1p" },
            new BookRef(){ Id = 60, Ref = "1pi" },
            new BookRef(){ Id = 60, Ref = "p1" },
            new BookRef(){ Id = 60, Ref = "pi1" },
            new BookRef(){ Id = 61, Ref = "2p" },
            new BookRef(){ Id = 61, Ref = "2pi" },
            new BookRef(){ Id = 61, Ref = "p2" },
            new BookRef(){ Id = 61, Ref = "pi2" },
            new BookRef(){ Id = 62, Ref = "1j" },
            new BookRef(){ Id = 62, Ref = "1jn" },
            new BookRef(){ Id = 62, Ref = "j1" },
            new BookRef(){ Id = 62, Ref = "jn1" },
            new BookRef(){ Id = 63, Ref = "2j" },
            new BookRef(){ Id = 63, Ref = "2jn" },
            new BookRef(){ Id = 63, Ref = "j2" },
            new BookRef(){ Id = 63, Ref = "jn2" },
            new BookRef(){ Id = 64, Ref = "3j" },
            new BookRef(){ Id = 64, Ref = "3jn" },
            new BookRef(){ Id = 64, Ref = "j3" },
            new BookRef(){ Id = 64, Ref = "jn3" },
            new BookRef(){ Id = 65, Ref = "jd" },
            new BookRef(){ Id = 65, Ref = "jud" },
            new BookRef(){ Id = 66, Ref = "ap" },
        };
    }
}
